image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - java -jar ./artifacts/app-ibank-build-for-testers.jar &
  - chmod +x gradlew


build_script:
  - ./gradlew test -Dselenide.headless=true --info